exports.UserStatuses = [
  'new_user',
  'verified',
  'unverified',
  'deleted',
];

exports.ProfileStatuses = [
  'auto-generated',
  'verified',
];

exports.Genders = [
  'Nam',
  'Nữ',
];

exports.Cities = [
  'An Giang',
  'Bình Dương',
  'Bình Phước',
  'Bình Thuận',
  'Bình Định',
  'Bà Rịa - Vũng Tàu',
  'Bạc Liêu',
  'Bắc Cạn',
  'Bắc Giang',
  'Bắc Ninh',
  'Bến Tre',
  'Cao Bằng',
  'Cà Mau',
  'Cần Thơ',
  'Điện Biên',
  'Đà Nẵng',
  'Đắc Lắc',
  'Đắk Nông',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Thừa Thiên - Huế',
  'Hà Giang',
  'Hà Nam',
  'Hà Nội',
  'Hà Tĩnh',
  'Hòa Bình',
  'Hưng Yên',
  'Hải Dương',
  'Hải Phòng',
  'Hậu Giang',
  'Khánh Hòa',
  'Kiên Giang',
  'Kon Tum',
  'Lai Châu',
  'Long An',
  'Lào Cai',
  'Lâm Đồng',
  'Lạng Sơn',
  'Nam Định',
  'Nghệ An',
  'Ninh Bình',
  'Ninh Thuận',
  'Phú Thọ',
  'Phú Yên',
  'Quảng Bình',
  'Quảng Nam',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Quảng Trị',
  'Sóc Trăng',
  'Sơn La',
  'TP Hồ Chí Minh',
  'Thanh Hoá',
  'Thái Bình',
  'Thái Nguyên',
  'Tiền Giang',
  'Trà Vinh',
  'Tuyên Quang',
  'Tây Ninh',
  'Vĩnh Long',
  'Vĩnh Phúc',
  'Yên Bái',
];

exports.Industries = [
  'Biên tập - Báo chí - Truyền hình',
  'Bán hàng',
  'Bưu chính',
  'Bảo hiểm - Tư vấn bảo hiểm',
  'Bảo vệ - An ninh - Vệ sỹ',
  'Bất động sản',
  'Công chức - Viên chức',
  'Công nghiệp',
  'Công nghệ cao',
  'Cơ khí - Chế tạo',
  'Du lịch',
  'Dầu khí - Hóa chất',
  'Dệt may - Da giày',
  'Dịch vụ',
  'Freelance',
  'Giao nhận - Vận chuyển - Kho bãi',
  'Giáo dục - Đào tạo',
  'Hoạch định - Dự án',
  'Hàng gia dụng',
  'Hàng hải',
  'Hàng không',
  'Hành chính - Văn phòng',
  'Hóa học - Sinh học',
  'IT phần cứng - mạng',
  'IT phần mềm',
  'In ấn - Xuất bản',
  'Khách sạn - Nhà hàng',
  'Kiến trúc - Thiết kế nội thất',
  'Kế toán - Kiểm toán',
  'Kỹ thuật',
  'Kỹ thuật ứng dụng',
  'Lao động phổ thông',
  'Làm đẹp - Thể lực - Spa',
  'Lập trình Games',
  'Marketing - PR',
  'Môi trường',
  'Mỹ phẩm - Trang sức',
  'Nghệ thuật - Điện ảnh',
  'Ngân hàng - Tài Chính',
  'Người giúp việc - Phục vụ - Tạp vụ',
  'Nhân sự',
  'Nhân viên kinh doanh',
  'Nông - Lâm - Ngư nghiệp',
  'Phiên dịch - Ngoại ngữ',
  'Pháp luật - Pháp lý',
  'Phát triển thị trường',
  'Promotion Girls - Boys',
  'QA-QC - Thẩm định - Giám định',
  'Quan hệ đối ngoại',
  'Quản trị kinh doanh',
  'Thiết kế - Mỹ thuật',
  'Thiết kế đồ họa - Web',
  'Thư ký - Trợ lý',
  'Thương mại điện tử',
  'Thể dục - Thể thao',
  'Thời trang',
  'Thực phẩm - Đồ uống',
  'Tiếp thị - Quảng cáo',
  'Tư vấn - Chăm sóc khách hàng',
  'Tổ chức sự kiện - Quà tặng',
  'Việc làm cấp cao',
  'Vận tải - Lái xe - Tài xế',
  'Vật tư - Thiết bị - Mua hàng',
  'Xuất - Nhập khẩu',
  'Xuất khẩu lao động',
  'Xây dựng',
  'Y tế - Dược',
  'Ô tô - Xe máy',
  'Điện - Điện tử - Điện lạnh',
  'Điện tử viễn thông',
  'Đầu tư',
];

exports.Positions = [
  'Mới tốt nghiệp / Thực tập sinh',
  'Nhân viên',
  'Trưởng nhóm',
  'Trưởng phòng',
  'Quản lý',
  'Phó giám đốc',
  'Giám đốc',
  'Khác',
];

exports.AcademicLevels = [
  'Lao động tự do',
  'Trung học cơ sở',
  'Trung học phổ thông',
  'Trung cấp',
  'Cao đẳng',
  'Cử nhân',
  'Kỹ sư',
  'Thạc sĩ',
];
